//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reminder.Storage.SqlServer.ADO.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reminder.Storage.SqlServer.ADO.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на INSERT INTO [dbo].[ReminderItem](
        ///[Id],
        ///[ContactId],
        ///[TargetDate],
        ///[Message],
        ///[StatusId],
        ///[CreatedDate],
        ///[UpdatedDate])
        ///
        ///VALUES(&apos;00000000-0000-0000-0000-111111111111&apos;,
        ///&apos;ContactId_1&apos;,
        ///&apos;2020-01-01 00:00:00 +00:00&apos;,
        ///&apos;Message_1&apos;,
        ///0,
        ///&apos;2019-01-01 00:00:00 +00:00&apos;,
        ///&apos;2019-01-01 00:00:00 +00:00&apos;).
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на --CREATE DATABASE [Reminder];
        ///--GO
        ///USE [Reminder];
        ///GO
        ///-- drop foreign key
        ///IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[ReminderItem]&apos;) AND type in (N&apos;U&apos;))
        ///	ALTER TABLE [dbo].[ReminderItem] DROP CONSTRAINT IF EXISTS [FK_ReminderItem_StatusId]
        ///GO
        ///--
        ///-- (Re-)create [dbo].[ReminderItem]
        ///IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[ReminderItem]&apos;) AND type in (N&apos;U&apos;))
        ///	DROP TABLE [dbo].[ReminderItem]
        ///GO
        ///CREATE TABLE [dbo].[ReminderItem] (
        ///	[ [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string L31_ClassWork_Reminder_schema {
            get {
                return ResourceManager.GetString("L31_ClassWork_Reminder_schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DROP PROCEDURE IF EXISTS [dbo].[AddReminderItem]
        ///GO
        ///CREATE PROCEDURE [dbo].[AddReminderItem](
        ///@contactId VARCHAR (50),
        ///@targetDate DATETIMEOFFSET,
        ///@message NVARCHAR (200),
        ///@statusId TINYINT ,
        ///@reminderId UNIQUEIDENTIFIER OUTPUT)
        ///AS BEGIN
        ///	SET NOCOUNT ON
        ///
        ///	DECLARE
        ///		@tempReminderItemId AS UNIQUEIDENTIFIER,
        ///		@now AS DATETIMEFFSET
        ///	SELECT
        ///		@tempReminderItemId = NEWID(),
        ///		@now = SYSDATETIMEOFFSET()
        ///
        ///INSERT INTO [dbo].[ReminderItem](
        ///[Id],
        ///[ContactId],
        ///[TargetDate],
        ///[Message],
        ///[StatusId [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string SPs {
            get {
                return ResourceManager.GetString("SPs", resourceCulture);
            }
        }
    }
}
